

#ifndef __C_VK_EVENTS
#define __C_VK_EVENTS

enum EventType
{
    VK_EVENT_MESSAGE_DELETED = 0,
    VK_EVENT_MESSAGE_FLAGS_CHANGED = 1,
    VK_EVENT_MESSAGE_FLAGS_ADDED = 2,
    VK_EVENT_MESSAGE_FLAGS_REMOVED = 3,
    VK_EVENT_MESSAGE_ADDED = 4,
    VK_EVENT_FRIEND_ONLINE = 8,
    VK_EVENT_FRIEND_OFFLINE = 9,
    VK_EVENT_CHAT_MODIFIED = 51,
    VK_EVENT_USER_TYPING = 61,
    VK_EVENT_USER_STARTED_TYPING = 62,
    VK_EVENT_NEW_VOIP_CALL = 70
};

#endif